### PR TITLE
Add tests to login controller

### PR DESCRIPTION
**Pull request by skosman**
Also extract object creation into functions to help with testing

Closes https://github.com/seng426-team3/vega-spring/issues/61

### CODE REVIEW

**Review by AntonNiko — APPROVED** [review]

**Comment by AntonNiko** [comment]
Approved. Looks like some of our unit tests are failling so need to get a fix for that in before Monday.

**Review by AntonNiko — CHANGES_REQUESTED** [review]
Seems like the duplicate user register error throws the exception but isn't handled properly perhaps?

**Comment by skosman** [comment]
> Seems like the duplicate user register error throws the exception but isn't handled properly perhaps?

Sorry I'll update the PR to handle it appropriately

**Review by AntonNiko — APPROVED** [review]
Looks great!

**Review by kianapaz — APPROVED** [review]
Looks awesome thank you!

**Pull request merged**
